@dev = http://localhost:4000

###
// Test de la route pour afficher tous les users
GET {{dev}}/

###
// Test de la route pour créer un user
POST {{dev}}/users/signup
Content-Type: application/json

{
    "name" : "Jean-Pierre Non",
    "email": "allo@allo.com",
    "password": "1235"
}

###
// Test de la route pour afficher un user (grâce à son id)
GET  {{dev}}/6249b700cdc7ab2582e212ec

###
// Test de la route pour modifier un user
PUT  {{dev}}/6249b700cdc7ab2582e212ec
Content-Type: application/json

{
    "name" : "Jean-Pierre Mouais",
    "email": "allo@allo.com",
    "password": "1235"
}

###

###
// Test de la route pour supprimer un user
DELETE  {{dev}}/6249b700cdc7ab2582e212ec

###


