@dev = http://localhost:4000

###
// Test de la route pour afficher tous les users
GET {{dev}}/users

###
// Test de la route pour créer un user
POST {{dev}}/users/signup
Content-Type: application/json

{
    "name" : "Jean-Pierre Non",
    "email": "allo@allo.com",
    "password": "1235"
}

###
// Test de la route pour afficher un user (grâce à son id)
GET  {{dev}}/users/6249b6b87cb07d0ee742cc7b

###
// Test de la route pour modifier un user
PUT  {{dev}}/users/6249b6b87cb07d0ee742cc7b
Content-Type: application/json

{
    "name" : "Jean-Pierre Mouais",
    "email": "allo@allo.com",
    "password": "1235"
}

###

###
// Test de la route pour supprimer un user
DELETE  {{dev}}/users/6249b6b87cb07d0ee742cc7b

###


